//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOVIN
    {
        public BOVIN()
        {
            this.GESTATION = new HashSet<GESTATION>();
            this.HISTORIQUE_MALADIE = new HashSet<HISTORIQUE_MALADIE>();
            this.PRODUCTION_BOVIN = new HashSet<PRODUCTION_BOVIN>();
        }
    
        public string IDBOVIN { get; set; }
        public int IDTYPEBOVIN { get; set; }
        public int IDTROUPEAU { get; set; }
        public int ID_STATUT { get; set; }
        public int ACTIF { get; set; }
        public int AGE { get; set; }
        public Nullable<int> PARENT_MAL { get; set; }
        public Nullable<int> PARENT_FEM { get; set; }
        public string SEXE { get; set; }
    
        public virtual TROUPEAU TROUPEAU { get; set; }
        public virtual STATUT STATUT { get; set; }
        public virtual TYPEBOVINS TYPEBOVINS { get; set; }
        public virtual ICollection<GESTATION> GESTATION { get; set; }
        public virtual ICollection<HISTORIQUE_MALADIE> HISTORIQUE_MALADIE { get; set; }
        public virtual ICollection<PRODUCTION_BOVIN> PRODUCTION_BOVIN { get; set; }
    }
}
