//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CattleProduction
    {
        public int IdCattleProduction { get; set; }
        public string IdCattle { get; set; }
        public System.DateTime DateProd { get; set; }
        public System.DateTime HourProd { get; set; }
        public double QuantityProd { get; set; }
    
        public virtual Cattle Cattle { get; set; }
    }
}
