//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dairy_farmEntities1 : DbContext
    {
        public dairy_farmEntities1()
            : base("name=dairy_farmEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOVIN> BOVIN { get; set; }
        public DbSet<GESTATION> GESTATION { get; set; }
        public DbSet<HISTORIQUE_MALADIE> HISTORIQUE_MALADIE { get; set; }
        public DbSet<MALADIE> MALADIE { get; set; }
        public DbSet<NOURRITURE_CONSOMMER> NOURRITURE_CONSOMMER { get; set; }
        public DbSet<PRODUCTION_BOVIN> PRODUCTION_BOVIN { get; set; }
        public DbSet<STATUT> STATUT { get; set; }
        public DbSet<STOCK_NOURRITURE> STOCK_NOURRITURE { get; set; }
        public DbSet<TROUPEAU> TROUPEAU { get; set; }
        public DbSet<TYPEBOVINS> TYPEBOVINS { get; set; }
    }
}
