//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disease
    {
        public Disease()
        {
            this.DiseaseHistories = new HashSet<DiseaseHistory>();
        }
    
        public int IdDisease { get; set; }
        public string Name { get; set; }
        public bool Contagious { get; set; }
    
        public virtual ICollection<DiseaseHistory> DiseaseHistories { get; set; }
    }
}
