//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestation
    {
        public int idGestation { get; set; }
        public string idCattle { get; set; }
        public System.DateTime dateBeginGest { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public System.DateTime dateCalve { get; set; }
        public string calveSex { get; set; }
        public string comment { get; set; }
    
        public virtual Cattle Cattle { get; set; }
    }
}
