//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestation
    {
        public int IdGestation { get; set; }
        public string IdCattle { get; set; }
        public System.DateTime DateBeginGest { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public System.DateTime DateCalve { get; set; }
        public string CalveSex { get; set; }
        public string Comment { get; set; }
    
        public virtual Cattle Cattle { get; set; }
    }
}
