//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTATION
    {
        public int ID_GESTATION { get; set; }
        public string IDBOVIN { get; set; }
        public System.DateTime DATE_DEBUT_GEST { get; set; }
        public Nullable<System.DateTime> DATE_FIN_GEST { get; set; }
        public System.DateTime DATE_ACCOUCHEMENT { get; set; }
        public string SEXE_FOETUS { get; set; }
        public string COMMENTAIRE { get; set; }
    
        public virtual BOVIN BOVIN { get; set; }
    }
}
