//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthStatu
    {
        public HealthStatu()
        {
            this.Cattle = new HashSet<Cattle>();
        }
    
        public int IdStatus { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Cattle> Cattle { get; set; }
    }
}
