//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Herd
    {
        public Herd()
        {
            this.Cattle = new HashSet<Cattle>();
            this.FoodComsuptions = new HashSet<FoodComsuption>();
        }
    
        public int IdHerd { get; set; }
        public int IdCattleType { get; set; }
        public int MaxCows { get; set; }
    
        public virtual ICollection<Cattle> Cattle { get; set; }
        public virtual CattleType CattleType { get; set; }
        public virtual ICollection<FoodComsuption> FoodComsuptions { get; set; }
    }
}
