//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MALADIE
    {
        public MALADIE()
        {
            this.HISTORIQUE_MALADIE = new HashSet<HISTORIQUE_MALADIE>();
        }
    
        public int ID_MALADIE { get; set; }
        public string NAME { get; set; }
        public bool CONTAGIEUX { get; set; }
    
        public virtual ICollection<HISTORIQUE_MALADIE> HISTORIQUE_MALADIE { get; set; }
    }
}
