//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOURRITURE_CONSOMMER
    {
        public int ID_NOURRITURE { get; set; }
        public int IDTROUPEAU { get; set; }
        public System.DateTime DATEDECONS { get; set; }
        public System.DateTime HEUREDECONS { get; set; }
        public double QUANTITE_CONS { get; set; }
    
        public virtual STOCK_NOURRITURE STOCK_NOURRITURE { get; set; }
        public virtual TROUPEAU TROUPEAU { get; set; }
    }
}
