//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTION_BOVIN
    {
        public int ID_PRODUCTION_BOV { get; set; }
        public string IDBOVIN { get; set; }
        public System.DateTime STARTMALADIE { get; set; }
        public System.DateTime HEURE { get; set; }
        public double QUANTITE { get; set; }
    
        public virtual BOVIN BOVIN { get; set; }
    }
}
