//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_NOURRITURE
    {
        public STOCK_NOURRITURE()
        {
            this.NOURRITURE_CONSOMMER = new HashSet<NOURRITURE_CONSOMMER>();
        }
    
        public int ID_NOURRITURE { get; set; }
        public double QUANTITE_TOT { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<NOURRITURE_CONSOMMER> NOURRITURE_CONSOMMER { get; set; }
    }
}
