//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TROUPEAU
    {
        public TROUPEAU()
        {
            this.BOVIN = new HashSet<BOVIN>();
            this.NOURRITURE_CONSOMMER = new HashSet<NOURRITURE_CONSOMMER>();
        }
    
        public int IDTROUPEAU { get; set; }
        public int IDTYPEBOVIN { get; set; }
        public int MAXBETES { get; set; }
    
        public virtual ICollection<BOVIN> BOVIN { get; set; }
        public virtual ICollection<NOURRITURE_CONSOMMER> NOURRITURE_CONSOMMER { get; set; }
        public virtual TYPEBOVINS TYPEBOVINS { get; set; }
    }
}
