//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dairy_farm_service
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPEBOVINS
    {
        public TYPEBOVINS()
        {
            this.BOVIN = new HashSet<BOVIN>();
            this.TROUPEAU = new HashSet<TROUPEAU>();
        }
    
        public int IDTYPEBOVIN { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<BOVIN> BOVIN { get; set; }
        public virtual ICollection<TROUPEAU> TROUPEAU { get; set; }
    }
}
